### ISSUE TITLE
python の version など

### ISSUE THREAD

**Issue by vipzero** [yotsugi-vip/Nico2py#1]
- [ ] .python-version の設置(~~pyenv local で固定~~)

- [x] pip freeze > requirements.txt

などがあると他の人が開発しやすい
(こっちで別の環境で動作確認してプルリクしてもアレだったので)

**Comment by vipzero** [comment]
ごめん最近 pipenv 使うと良さげらしい

**Comment by yotsugi-vip** [comment]
なるほど

**Comment by vipzero** [comment]
vertion が明記されたのでCloseする
